apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tpetkos-chatbot-test1 
  janus-idp.io/tekton: tpetkos-chatbot-test1
  backstage.io/kubernetes-id: tpetkos-chatbot-test1
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tpetkos-chatbot-test1
resources: 
- application-dev.yaml