---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: tpetkos-chatbot-test1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tpetkos-chatbot-test1 
  name: tpetkos-chatbot-test1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi