apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: tpetkos-chatbot-test1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tpetkos-chatbot-test1 
  name: tpetkos-chatbot-test1
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: tpetkos-chatbot-test1 
    weight: 100 
  wildcardPolicy: None
